[[Skia]]
arch = "aarch64"
git-tree-sha1 = "75aef0249c7d09c0ad398e14026ecd80a2449b85"
os = "macos"

    [[Skia.download]]
    sha256 = "cb0503ffabb887f7c163bb344a9a6088838023ec2a73f4ee50c590a388407e0a"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.aarch64-apple-darwin.tar.gz"
[[Skia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "725a5137aecd59ae672e46b0a09bca1220beb883"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "bed1b983b6ff2759b7eab7181003888b75cb92cdd965ef73e1c52e7a96582d98"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Skia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48e9b7165c245b62761d406acc46f2b6546ca725"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "7d7b995a5227ecc9c3c387418d8e2ca7faa6829b5bf936e207325db9032d598e"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Skia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6b32631078f5db69fb8883ed9440ef5edd0dfa3"
libc = "musl"
os = "linux"

    [[Skia.download]]
    sha256 = "214fb8140fe3cf310ef15dbd64bd84d8dfd11a409cbfa191c87313bbdc0003a3"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.aarch64-linux-musl-cxx11.tar.gz"
[[Skia]]
arch = "aarch64"
git-tree-sha1 = "d0cd8e52898d2cd3e32c2875c4fe6d1fd15e2da3"
os = "freebsd"

    [[Skia.download]]
    sha256 = "945c654757e8caa903e91f8a7635c8d2a07f4d87d33b2fdd1c3748f810210ee6"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.aarch64-unknown-freebsd.tar.gz"
[[Skia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc3bb41257db0ddfa7620e0e3ccd570707ac0f48"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "e2307b3566ca52782b6441183d0b84c6173d021e30cf58ce5ed7eb8822847832"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Skia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79ff939ac5260246ba86d0b04042c7bcbaa19064"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "e045f1abf8576807971523c241990e5b994519f8fb03b7c769a04496722376f1"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Skia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60b5b22420174671273f81664155a9325d0ca65e"
libc = "musl"
os = "linux"

    [[Skia.download]]
    sha256 = "e249af2ca8a413a036b79819311f94805dbb5ffa5aae715971eabc774f21b2db"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Skia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f2341557daf965a6594e42e4af30b2cbd82a49a"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "c7bf2d4cac4579f5d9c135d54fbbb8ab9e1f1d2777ce3f5d00d849d23f292a11"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Skia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65bd0ef3ae4ba3d86c7c72b6e7f34df5c898a013"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "3dab028f03d7a5161121e51a703768cf3742130079f6b3acefeb1ed87750a6ff"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Skia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fddc458bafcd0e2104d01d74b908cf04ddde258"
libc = "musl"
os = "linux"

    [[Skia.download]]
    sha256 = "2182f22641d62a16dc82809f0c12e4905ea7e26a8473cfd42ebef2f85a0f0037"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Skia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8cd33552a8a9eb45046ca8900c6c2dee02728bb"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "bb0bc2fe15e2e644155288fe25f7185851a28fa41b130e4c7a8cb72616789f1d"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.i686-linux-gnu-cxx03.tar.gz"
[[Skia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7c1d5915ea57681e9abd89ba30289305f1ee3f8"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "e15c0cbcf94ab2d04b02a70da6db19d9d0cdd72507b84fbfcbc7dca4d97a6001"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.i686-linux-gnu-cxx11.tar.gz"
[[Skia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e23771515f237491140a0f20ada482167f49826"
libc = "musl"
os = "linux"

    [[Skia.download]]
    sha256 = "1363c8622dac87033e019db849ff955ea5a8e3b3911774d4fafd1956302b410b"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.i686-linux-musl-cxx11.tar.gz"
[[Skia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42397fa89652fe6d2e8a5585546847659a688b55"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "75c421afd8d9231e117fb883e2d10d69c924c96a358fa131831c7668a242d7da"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Skia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed492d5270fe64640c027f368d734fb884ecdeaf"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "2f07d0a0d86cd0a1978c664db277c23a48d156902b625a3ef40c447cbf4dc74a"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Skia]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ca4c21d3240f5aea4f412c90e73d5b44266ff4c"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "63f04a5240df6c5e9ae36ad1d091f7c48204ab62905647d9724392d65aec30d1"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.riscv64-linux-gnu-cxx03.tar.gz"
[[Skia]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87fb4d0421a996c7c6e70066fbc1e3e875d9a14d"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "71e0d0c90b42844c23e3c151cfe6ef255933036ecb3347e0b3a161f878a6dfa5"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.riscv64-linux-gnu-cxx11.tar.gz"
[[Skia]]
arch = "x86_64"
git-tree-sha1 = "b78fc176d6d55b3fe26e34d1d237782e2c6edcf6"
os = "macos"

    [[Skia.download]]
    sha256 = "3e86c923ca54fbaaa2026c68abafa9faf326cd2c1359ce6d3ca1f276245c0357"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.x86_64-apple-darwin.tar.gz"
[[Skia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3846112c2a50ebf733a1f2162dbe526785006902"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "b94ead182f2e8ed375e81366fd513523eca77d6fad905dec4b36c966f3c93201"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Skia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "064cdded2efa409f41bbfcc99b4888f6b3f1559e"
libc = "glibc"
os = "linux"

    [[Skia.download]]
    sha256 = "42f467492c3e3c151883ea316289407b7ca37daf020fc80c82ac3648e99687a4"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Skia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c636ec1adaecd385e2abb2f3a81c382e5befb64"
libc = "musl"
os = "linux"

    [[Skia.download]]
    sha256 = "44d08a0effebfc3880fd3bb4823ffa9472dd8c4d6e2c59450006062f5689cd2e"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.x86_64-linux-musl-cxx11.tar.gz"
[[Skia]]
arch = "x86_64"
git-tree-sha1 = "a28e6e74cdd05d51e58106c94f3c7a873e15056f"
os = "freebsd"

    [[Skia.download]]
    sha256 = "096bdc0350a58831b9d29fb2f0f86cf68b6b832367e19ea976248dd6a361560e"
    url = "https://github.com/JuliaBinaryWrappers/Skia_jll.jl/releases/download/Skia-v0.40.1+0/Skia.v0.40.1.x86_64-unknown-freebsd.tar.gz"
