# Autogenerated wrapper script for Skia_jll for x86_64-linux-musl-cxx11
export libskia

using Fontconfig_jll
using JpegTurbo_jll
using libpng_jll
using libwebp_jll
using ICU_jll
using Expat_jll
using Xorg_libX11_jll
using xkbcommon_jll
using Libglvnd_jll
JLLWrappers.@generate_wrapper_header("Skia")
JLLWrappers.@declare_library_product(libskia, "libskia.so")
function __init__()
    JLLWrappers.@generate_init_header(Fontconfig_jll, JpegTurbo_jll, libpng_jll, libwebp_jll, ICU_jll, Expat_jll, Xorg_libX11_jll, xkbcommon_jll, Libglvnd_jll)
    JLLWrappers.@init_library_product(
        libskia,
        "lib/libskia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
